export const EMAIL_VERIFICATION_TOKEN_LENGTH = 32;
export const EMAIL_VERIFICATION_TOKEN_EXPIRY_DAYS = 1;

export const PASSWORD_RESET_TOKEN_LENGTH = 32;
export const PASSWORD_RESET_TOKEN_EXPIRY_HOURS = 1;
