export const DUMMY_PASSWORD_HASH = "$2b$10$CwTycUXWue0Thq9StjUM0uJ8l1v5nG5F5Z7a8Z/7v7K5zF5wzjE3e";

export const EMAIL_VERIFICATION_TOKEN_LENGTH = 32;
export const EMAIL_VERIFICATION_TOKEN_EXPIRY_DAYS = 1;

export const PASSWORD_RESET_TOKEN_LENGTH = 32;
export const PASSWORD_RESET_TOKEN_EXPIRY_HOURS = 1;
