export const DEBUG_CODES = {
  AUTH: {
    USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",

    ROLE_INVALID: "AUTH_ROLE_INVALID",

    HEADER_MISSING: "AUTH_HEADER_MISSING",
    ACCESS_TOKEN_MISSING: "AUTH_ACCESS_TOKEN_MISSING",
    ACCESS_TOKEN_EXPIRED: "AUTH_ACCESS_TOKEN_EXPIRED",
    ACCESS_TOKEN_INVALID: "AUTH_ACCESS_TOKEN_INVALID",
    ACCESS_TOKEN_MALFORMED: "AUTH_ACCESS_TOKEN_MALFORMED",
    ACCESS_TOKEN_UNEXPECTED_ERROR: "AUTH_ACCESS_TOKEN_UNEXPECTED_ERROR",

    REFRESH_TOKEN_MISSING: "AUTH_REFRESH_TOKEN_MISSING",
    REFRESH_TOKEN_NOT_FOUND: "AUTH_REFRESH_TOKEN_NOT_FOUND",
    REFRESH_TOKEN_REUSED: "AUTH_REFRESH_TOKEN_REUSED",
    REFRESH_TOKEN_REVOKED: "AUTH_REFRESH_TOKEN_REVOKED",
    REFRESH_TOKEN_EXPIRED: "AUTH_REFRESH_TOKEN_EXPIRED",

    EMAIL_VERIFICATION_TOKEN_NOT_FOUND: "AUTH_EMAIL_VERIFICATION_TOKEN_NOT_FOUND",
    EMAIL_VERIFICATION_TOKEN_INVALID: "AUTH_EMAIL_VERIFICATION_TOKEN_INVALID",
    EMAIL_VERIFICATION_TOKEN_ALREADY_USED: "AUTH_EMAIL_VERIFICATION_TOKEN_ALREADY_USED",
    EMAIL_VERIFICATION_TOKEN_EXPIRED: "AUTH_EMAIL_VERIFICATION_TOKEN_EXPIRED",

    PASSWORD_RESET_TOKEN_NOT_FOUND: "AUTH_PASSWORD_RESET_TOKEN_NOT_FOUND",
    PASSWORD_RESET_TOKEN_INVALID: "AUTH_PASSWORD_RESET_TOKEN_INVALID",
    PASSWORD_RESET_TOKEN_ALREADY_USED: "AUTH_PASSWORD_RESET_TOKEN_ALREADY_USED",
    PASSWORD_RESET_TOKEN_EXPIRED: "AUTH_PASSWORD_RESET_TOKEN_EXPIRED",
  },
} as const;
