SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS rides;
DROP TABLE IF EXISTS preferences;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS vehicles;
DROP TABLE IF EXISTS vehicle_brands;
DROP TABLE IF EXISTS vehicle_colors;
DROP TABLE IF EXISTS vehicle_energies;

SET FOREIGN_KEY_CHECKS = 1;