import { StatsService } from "@/services";
import { catchAsync } from "@/utils";

import type { Request, Response } from "express";

/**
 * Handles the retrieval of the number of planned trips on the platform per day.
 */
export const getPlatformDailyTrips = catchAsync(async (req: Request, res: Response) => {
  const dailyTrips = await StatsService.getDailyTrips();

  res.status(200).json({
    success: true,
    data: dailyTrips,
  });
});

/**
 * Handles the retrieval of credits generated by the platform per day.
 */
export const getPlatformDailyCredits = catchAsync(async (req: Request, res: Response) => {
  const dailyCredits = await StatsService.getDailyCredits();

  res.status(200).json({
    success: true,
    data: dailyCredits,
  });
});

/**
 * Handles the retrieval of the total number of credits generated by the platform.
 */
export const getPlatformTotalCredits = catchAsync(async (req: Request, res: Response) => {
  const totalCredits = await StatsService.getTotalCredits();

  res.status(200).json({
    success: true,
    data: { totalCredits },
  });
});
