import { col, fn, literal, Op } from "sequelize";

import { PLATFORM_FEE_PER_SEAT } from "@/constants";
import { Booking, Trip } from "@/models";

export class StatsService {
  /**
   * Retrieves the number of planned trips for each day.
   *
   * Based on the departure date (`departure_datetime`) of trips created on the platform.
   *
   * @returns An array of objects containing the date and the number of trips planned for that day.
   * @example [{ date: "2025-07-01", count: 5 }, { date: "2025-07-02", count: 8 }]
   */
  public static async getDailyTrips(): Promise<{ date: string; count: number }[]> {
    const rows = (await Trip.findAll({
      attributes: [
        [fn("DATE", col("departure_datetime")), "date"],
        [fn("COUNT", col("id")), "count"],
      ],
      group: ["date"],
      order: [["date", "ASC"]],
      raw: true,
    })) as unknown as { date: string; count: string }[];

    return rows.map((r) => ({
      date: r.date,
      count: Number(r.count),
    }));
  }

  /**
   * Retrieves the number of credits generated per day by the platform.
   *
   * Each row indicates the total number of credits generated from trips
   * completed or awaiting feedback on that day.
   *
   * @returns An array of objects containing the date and credits generated on that date.
   * @example [{ date: "2025-07-01", credits: 30 }, { date: "2025-07-02", credits: 48 }]
   */
  public static async getDailyCredits(): Promise<{ date: string; credits: number }[]> {
    const rows = (await Booking.findAll({
      attributes: [
        [fn("DATE", col("trip.departure_datetime")), "date"],
        [literal(`SUM(seats_booked * ${PLATFORM_FEE_PER_SEAT})`), "credits"],
      ],
      include: [{ association: "trip", attributes: [], required: true }],
      where: {
        status: { [Op.in]: ["awaiting_feedback", "completed"] },
      },
      group: ["date"],
      order: [["date", "ASC"]],
      raw: true,
    })) as unknown as { date: string; credits: string }[];

    return rows.map((r) => ({
      date: r.date,
      credits: Number(r.credits),
    }));
  }

  /**
   * Calculates the total number of credits generated by the platform.
   *
   * Credits are counted for each seat booked on trips with status
   * "awaiting_feedback" or "completed", as in both cases, the platform takes its commission.
   *
   * @returns {Promise<number>} The total number of credits.
   */
  public static async getTotalCredits(): Promise<number> {
    const result = await Booking.sum("seats_booked", {
      where: { status: { [Op.in]: ["awaiting_feedback", "completed"] } },
    });

    return (result * PLATFORM_FEE_PER_SEAT) | 0;
  }
}
